export type GlobalCurrencyRow = {
	country: string;
	code: string;
	score: number;
};

export type CurrencySeedRow = {
	country: string;
	code: string;
	baseScore: number;
};

// Expanded universe (~100) used for daily ranking generation.
// Higher baseScore means stronger long-term baseline before daily adjustment.
export const globalCurrencyUniverse: CurrencySeedRow[] = [
	{ country: "Switzerland", code: "CHF", baseScore: 98.7 },
	{ country: "United States", code: "USD", baseScore: 97.5 },
	{ country: "Singapore", code: "SGD", baseScore: 95.1 },
	{ country: "Eurozone", code: "EUR", baseScore: 94.2 },
	{ country: "United Kingdom", code: "GBP", baseScore: 93.8 },
	{ country: "Canada", code: "CAD", baseScore: 92.3 },
	{ country: "Australia", code: "AUD", baseScore: 91.4 },
	{ country: "Norway", code: "NOK", baseScore: 90.7 },
	{ country: "Sweden", code: "SEK", baseScore: 89.9 },
	{ country: "Denmark", code: "DKK", baseScore: 89.1 },
	{ country: "Japan", code: "JPY", baseScore: 88.3 },
	{ country: "New Zealand", code: "NZD", baseScore: 87.5 },
	{ country: "United Arab Emirates", code: "AED", baseScore: 86.8 },
	{ country: "Saudi Arabia", code: "SAR", baseScore: 86.2 },
	{ country: "Qatar", code: "QAR", baseScore: 85.6 },
	{ country: "Israel", code: "ILS", baseScore: 84.9 },
	{ country: "Taiwan", code: "TWD", baseScore: 83.4 },
	{ country: "China", code: "CNY", baseScore: 82.7 },
	{ country: "Thailand", code: "THB", baseScore: 81.9 },
	{ country: "Malaysia", code: "MYR", baseScore: 81.2 },
	{ country: "Poland", code: "PLN", baseScore: 80.7 },
	{ country: "Czechia", code: "CZK", baseScore: 80.1 },
	{ country: "Hungary", code: "HUF", baseScore: 79.4 },
	{ country: "Romania", code: "RON", baseScore: 78.8 },
	{ country: "Korea", code: "KRW", baseScore: 78.1 },
	{ country: "Chile", code: "CLP", baseScore: 77.6 },
	{ country: "Mexico", code: "MXN", baseScore: 77.1 },
	{ country: "Peru", code: "PEN", baseScore: 76.6 },
	{ country: "Brazil", code: "BRL", baseScore: 76.1 },
	{ country: "South Africa", code: "ZAR", baseScore: 75.4 },
	{ country: "Colombia", code: "COP", baseScore: 74.8 },
	{ country: "India", code: "INR", baseScore: 74.3 },
	{ country: "Indonesia", code: "IDR", baseScore: 73.7 },
	{ country: "Philippines", code: "PHP", baseScore: 73.2 },
	{ country: "Vietnam", code: "VND", baseScore: 72.6 },
	{ country: "Russia", code: "RUB", baseScore: 71.9 },
	{ country: "Pakistan", code: "PKR", baseScore: 70.7 },
	{ country: "Egypt", code: "EGP", baseScore: 69.8 },
	{ country: "Sri Lanka", code: "LKR", baseScore: 68.4 },
	{ country: "Nigeria", code: "NGN", baseScore: 67.2 },
	{ country: "Ghana", code: "GHS", baseScore: 66.5 },
	{ country: "Morocco", code: "MAD", baseScore: 66.2 },
	{ country: "Kenya", code: "KES", baseScore: 66.0 },
	{ country: "Bangladesh", code: "BDT", baseScore: 65.9 },
	{ country: "Kazakhstan", code: "KZT", baseScore: 65.8 },
	{ country: "Ukraine", code: "UAH", baseScore: 65.8 },
	{ country: "Uzbekistan", code: "UZS", baseScore: 65.8 },
	{ country: "Ethiopia", code: "ETB", baseScore: 65.8 },
	{ country: "Turkey", code: "TRY", baseScore: 65.7 },
	{ country: "Argentina", code: "ARS", baseScore: 64.1 },
	{ country: "Bahrain", code: "BHD", baseScore: 63.8 },
	{ country: "Oman", code: "OMR", baseScore: 63.6 },
	{ country: "Kuwait", code: "KWD", baseScore: 63.4 },
	{ country: "Jordan", code: "JOD", baseScore: 63.2 },
	{ country: "Iceland", code: "ISK", baseScore: 63.0 },
	{ country: "Bulgaria", code: "BGN", baseScore: 62.8 },
	{ country: "Croatia", code: "HRK", baseScore: 62.6 },
	{ country: "Serbia", code: "RSD", baseScore: 62.4 },
	{ country: "Bosnia and Herzegovina", code: "BAM", baseScore: 62.2 },
	{ country: "Georgia", code: "GEL", baseScore: 62.0 },
	{ country: "Azerbaijan", code: "AZN", baseScore: 61.8 },
	{ country: "Armenia", code: "AMD", baseScore: 61.6 },
	{ country: "Moldova", code: "MDL", baseScore: 61.4 },
	{ country: "Belarus", code: "BYN", baseScore: 61.2 },
	{ country: "Algeria", code: "DZD", baseScore: 61.0 },
	{ country: "Tunisia", code: "TND", baseScore: 60.8 },
	{ country: "Lebanon", code: "LBP", baseScore: 60.6 },
	{ country: "Iraq", code: "IQD", baseScore: 60.4 },
	{ country: "Iran", code: "IRR", baseScore: 60.2 },
	{ country: "Nepal", code: "NPR", baseScore: 59.8 },
	{ country: "Mongolia", code: "MNT", baseScore: 59.6 },
	{ country: "Cambodia", code: "KHR", baseScore: 59.4 },
	{ country: "Myanmar", code: "MMK", baseScore: 59.2 },
	{ country: "Laos", code: "LAK", baseScore: 59.0 },
	{ country: "Brunei", code: "BND", baseScore: 58.8 },
	{ country: "Hong Kong", code: "HKD", baseScore: 58.6 },
	{ country: "Macao", code: "MOP", baseScore: 58.4 },
	{ country: "Papua New Guinea", code: "PGK", baseScore: 58.2 },
	{ country: "Fiji", code: "FJD", baseScore: 58.0 },
	{ country: "Jamaica", code: "JMD", baseScore: 57.8 },
	{ country: "Dominican Republic", code: "DOP", baseScore: 57.6 },
	{ country: "Costa Rica", code: "CRC", baseScore: 57.4 },
	{ country: "Guatemala", code: "GTQ", baseScore: 57.2 },
	{ country: "Honduras", code: "HNL", baseScore: 57.0 },
	{ country: "Paraguay", code: "PYG", baseScore: 56.8 },
	{ country: "Uruguay", code: "UYU", baseScore: 56.6 },
	{ country: "Bolivia", code: "BOB", baseScore: 56.4 },
	{ country: "Trinidad and Tobago", code: "TTD", baseScore: 56.2 },
	{ country: "Mauritius", code: "MUR", baseScore: 56.0 },
	{ country: "Namibia", code: "NAD", baseScore: 55.8 },
	{ country: "Rwanda", code: "RWF", baseScore: 55.6 },
	{ country: "Uganda", code: "UGX", baseScore: 55.4 },
	{ country: "Tanzania", code: "TZS", baseScore: 55.2 },
	{ country: "Zambia", code: "ZMW", baseScore: 55.0 },
	{ country: "CFA Franc BEAC", code: "XAF", baseScore: 54.8 },
	{ country: "CFA Franc BCEAO", code: "XOF", baseScore: 54.6 },
	{ country: "East Caribbean", code: "XCD", baseScore: 54.4 },
	{ country: "CFP Franc", code: "XPF", baseScore: 54.2 },
	{ country: "Yemen", code: "YER", baseScore: 54.0 },
	{ country: "Burundi", code: "BIF", baseScore: 53.8 },
	{ country: "Congo", code: "CDF", baseScore: 53.6 },
	{ country: "Mozambique", code: "MZN", baseScore: 53.4 },
	{ country: "Sudan", code: "SDG", baseScore: 53.2 },
	{ country: "Syria", code: "SYP", baseScore: 53.0 },
	{ country: "Afghanistan", code: "AFN", baseScore: 52.8 },
	{ country: "Somalia", code: "SOS", baseScore: 52.6 },
	{ country: "Venezuela", code: "VES", baseScore: 52.4 },
	{ country: "Libya", code: "LYD", baseScore: 52.2 },
	{ country: "Suriname", code: "SRD", baseScore: 52.0 },
];

export const globalCurrencyRanking: GlobalCurrencyRow[] =
	globalCurrencyUniverse.map((item) => ({
		country: item.country,
		code: item.code,
		score: item.baseScore,
	}));

export const sortedGlobalCurrencies = [...globalCurrencyRanking].sort(
	(a, b) => b.score - a.score,
);

export const krwRank =
	sortedGlobalCurrencies.findIndex((item) => item.code === "KRW") + 1;
